name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
      inputs:
        skip_upload:
          description: "Select whether the upload process should be skipped"
          required: true
          default: "false"
          type: choice
          options:
          - "true"
          - "false"

permissions: write-all

env:
  SKIP_UPLOAD: ${{ github.event.inputs.skip_upload || false }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: docker build . -t ghcr.io/${GITHUB_REPOSITORY,,}
      - name: Publish
        run: |
          if [ "${{ env.SKIP_UPLOAD }}" == "false"  ]; then
            docker push ghcr.io/${GITHUB_REPOSITORY,,}
          else
            echo "[ * ] Docker image upload skipped."
          fi
